- name: Install HAProxy and Keepalived
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - haproxy
    - keepalived

- name: Copy HAProxy configuration file
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

- name: Copy Keepalived configuration file
  template:
    src: templates/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart Keepalived

