apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: production
  source:
    repoURL: https://github.com/quent36987/minikube.git
    targetRevision: HEAD
    path: kube/traefik-setup

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true

