apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projet
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quent36987/minikube.git
    targetRevision: HEAD
    path: kube/projet

  destination:
    namespace: app
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true

