apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quent36987/minikube
    targetRevision: HEAD
    path: kube
   # helm:
   #   valueFiles:
   #     - traefik-values.yaml
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true

