apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.toml: |
    [http]
    [http.services]
      [http.services.my-service.loadBalancer]
        [[http.services.my-service.loadBalancer.servers]]
          url = "http://gitlab.exemple"

    [providers]
      [providers.kubernetesCRD]
        ingressClass = "traefik"
