---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: projet-ingress
  namespace: app
spec:
  entryPoints:
    - websecure
    - web
  routes:
    - kind: Rule
      match: Host(`projet.home.quentinou.ovh`)
      priority: 10
      services:
        - name: pgadmin
          port: 80
    - kind: Rule
      match: Host(`projet.home.quentinou.ovh`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: pgadmin
          port: 80
          scheme: h2c
