- name: Create ArgoCD namespace
  ignore_errors: yes
  ansible.builtin.command:
    cmd: "kubectl create namespace argocd"

- name: Install ArgoCD
  ansible.builtin.command:
    cmd: "kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"

- name: Wait for ArgoCD to be ready
  ansible.builtin.command:
    argv:
      - kubectl
      - wait
      - -n
      - argocd
      - --for=condition=available
      - --timeout=0
      - --all
      - deploy
  register: result
  until: result.rc == 0
  retries: 40
  delay: 10
  check_mode: false
  changed_when: false

- name: Set Argo CD admin password
  ansible.builtin.command: >
    kubectl -n argocd patch secret argocd-secret
    -p '{"stringData": {
    "admin.password": "$2a$10$9THUzMQ4ddHwiPMImFZPVOXQTH6du6VuKnusYVMa7J0eBtQD6Su5e",
    "admin.passwordMtime": "'$(date +%FT%T%Z)'"
    }}'
