- name: Create ArgoCD namespace
  ignore_errors: yes
  ansible.builtin.command:
    cmd: "kubectl create namespace argocd"

- name: Install ArgoCD
  ansible.builtin.command:
    cmd: "kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
