- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Clone my argocd repo
  ansible.builtin.git:
    repo: "{{ repo_github }}"
    dest: "{{ dest_github }}"
    force: yes

- name: Install ArgoCD
  ansible.builtin.command:
    cmd: "kubectl apply -k {{ argocd_repo }}"

- name: Wait for ArgoCD to be ready
  ansible.builtin.command:
    argv:
      - kubectl
      - wait
      - -n
      - argocd
      - --for=condition=available
      - --timeout=0
      - --all
      - deploy
  register: result
  until: result.rc == 0
  retries: 20
  delay: 10
  check_mode: false
  changed_when: false

- name: Set Argo CD admin password
  ansible.builtin.command: >
    kubectl -n argocd patch secret argocd-secret  
    -p '{"stringData": {
    "admin.password": "{{ password_argocd }}",
    "admin.passwordMtime": "{{ passwordMtime_argocd }}"
    }}'

- name: Create ArgoCD application (my git repo)
  ansible.builtin.command:
    argv:
      - kubectl
      - apply
      - -n
      - argocd
      - -f
      - https://raw.githubusercontent.com/quent36987/minikube/master/kube/application.yaml


