apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/quent36987/minikube/master/kube/values.yaml
    repoURL: https://traefik.github.io/charts
    targetRevision: v23.0.1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
