apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: argo-config
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/dynatrace-oss/progressivedelivery-masterclass.git'
    targetRevision: main
    path: "kube/argo-cd-config"
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
