apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-setup
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/quent36987/minikube
    targetRevision: HEAD
    path: kube/traefik-setup

  destination:
    server: https://kubernetes.default.svc
    namespace: app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
