apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik
  namespace: app
spec:
    ingressClassName: "traefik"
    rules:
      - host: "argo.home.quentinou.ovh"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: argocd-server
                  port:
                    number: 80

