services:
  ansible:
    container_name: ansible
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    volumes:
      - ./ansible:/usr/ansible
      - ~/.ssh:/root/.ssh

